### ISSUE TITLE
Add DDL capabilities

### ISSUE THREAD

**Issue by akash-kaul** [pyTigerGraph/pyTigerGraph#11]
**Is your feature request related to a problem? Please describe.**
I would like to submit a data payload to the endpoint that uses TigerGraph's DDL functionality

**Describe the solution you'd like**
[Post /ddl/graphname -run a loading job](https://docs.tigergraph.com/dev/restpp-api/built-in-endpoints#post-ddl-graph_name-run-a-loading-job)

**Describe alternatives you've considered**
Tried to load data on the cloud but due to restricted server access I am unable to load the data directly from a Jupyter notebook to the TigerGraph cloud instance

**Additional context**
Building widgets for pyTigerGraph

**Comment by parkererickson** [comment]
@akash-kaul - @HerkTG said that you have already written the DDL stuff in Python - want to open a PR with it?

**Comment by akash-kaul** [comment]
@parkererickson actually I think don't know if DDL is worth it. I was only able to get it to work using a specific format for the loading jobs, and I don't think it's generalizable. But basically you make a post request to the URL:9000/ddl/graphname

**Comment by parkererickson** [comment]
@akash-kaul If it is just a matter of having a loading job installed, I would say take a stab at it. It would be cool to define a loading job for a dataframe then run the ddl on the dataframe.

**Comment by HerkTG** [comment]
That's a good idea!! ->  define a loading job for a dataframe



*Jon Herke*
Developer/Technical Evangelist, TigerGraph
+1 (507) 351-4434  | www.tigergraph.com


*Join us for Graph + AI World Conference 2020 - graphaiworld.com
<http://graphaiworld.com/> *

**Comment by zrougamed** [comment]
DDL upload added in v0.0.9.6.7 
function uploadfile
