### ISSUE TITLE
getVer() fails when no token is available.

### ISSUE THREAD

**Issue by yaniv256** [pyTigerGraph/pyTigerGraph#13]
For example, when running GSQL101.ipynb we get this error:

<img width="1006" alt="Screen Shot 2020-08-07 at 9 28 36 PM" src="https://user-images.githubusercontent.com/2006481/89700604-10489200-d8f5-11ea-926e-9cf02c15dd33.png">

Expanded stack:
<img width="999" alt="Screen Shot 2020-08-07 at 9 31 58 PM" src="https://user-images.githubusercontent.com/2006481/89700649-8cdb7080-d8f5-11ea-82a4-3c35a3b489c4.png">

**Comment by parkererickson** [comment]
Fixed in v0.0.8.1. See #14 for more details. Optional "version" parameter in gsql function to fix this behavior.
