### ISSUE TITLE
Couldn't connect tigerDB

### ISSUE THREAD

**Issue by lifeisgoodcdj** [pyTigerGraph/pyTigerGraph#31]
Recently I deployed a cluster of TigerGraphDB, including 3 nodes. And everything seems running correctly, Also check DB status by "gadmin status" and each item shows  a word "Running"  .
Version of tigergraph DB is 3.0.6 with just a temporary license.
But this pyTigerGraph pkg doesn't connect to tigerDB.
The whole command as below,
"
import pyTigerGraph as tg
conn = tg.TigerGraphConnction(host='http://localhost', graphname='social', username='tigergraph',password='tigergraph')
conn.getSchema()
"
When I execute the last line "conn.getSchema()" , it won't stop and show any result , just like suspending forever, no response.
In addition , I have tried curl -X GET "http://10.116.85.xxx:9000/version 
and GraphStudio could be opened.

Is this version of pyTigerGraph 0.0.9.6.3 is not compatible with newly TigerGraph3.0.6 ?

**Comment by HerkTG** [comment]
@lifeisgoodcdj I'll dive into this a bit deeper. What Operating System are you running?

In the meantime can you test pyTigerGraphBeta to see if it's working as expected. We are removing the JAVA dependency in the Beta version and should be released shortly to the pyTigerGraph official (community supported) package. 

[Video Walkthrough of using pyTigerGraphBeta](https://www.youtube.com/watch?v=cEVbaivITUw&t=26s)
[Sample Notebook 1 using pyTigerGraphBeta](https://colab.research.google.com/drive/1QnYXgypDYKMxuGfMLEtWcIVkp61njkrw?usp=sharing)
[Sample Notebook 2 using pyTigerGraphBeta](https://colab.research.google.com/drive/1iKtauUoMCPOR7f2ExO70gQOJ_LWwWIp4?usp=sharing)

**Comment by lifeisgoodcdj** [comment]
Thank you! 
I have reinstalled version-beta based on your information. 
conn.getSchema()  works
But conn.gsql('ls') failed which shows as below:
"
File "root/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
     sock.connect(sa)
ConnectionRefusedError: [Errorno 111] Connection refused
"

**Comment by lifeisgoodcdj** [comment]
Thank you!
I have reinstalled version-beta based on your information.
conn.getSchema() works
But conn.gsql('ls') failed which shows as below:
"
File "root/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errorno 111] Connection refused
"




***@***.***
 
From: HerkTG
Date: 2021-03-30 09:03
To: pyTigerGraph/pyTigerGraph
CC: lifeisgoodcdj; Mention
Subject: Re: [pyTigerGraph/pyTigerGraph] Couldn't connect tigerDB (#31)
@lifeisgoodcdj I'll dive into this a bit deeper. What Operating System are you running?
In the meantime can you test pyTigerGraphBeta to see if it's working as expected. We are removing the JAVA dependency in the Beta version and should be released shortly to the pyTigerGraph official (community supported) package.
Video Walkthrough of using pyTigerGraphBeta
Sample Notebook 1 using pyTigerGraphBeta
Sample Notebook 2 using pyTigerGraphBeta

**Comment by HerkTG** [comment]
@lifeisgoodcdj can you try `print(conn.gsql('''LS''', options=[]))`

**Comment by parkererickson** [comment]
I think you are missing changing the hostname from "localhost" to your IP address specified, along with the graphname, username, and password. For example, this should be correct code: 
```py
import pyTigerGraph as tg
conn = tg.TigerGraphConnction(host="http://10.116.85.xxx", graphname='YOUR_GRAPH_NAME_HERE', username='YOUR_USERNAME_HERE', password='YOUR_PASSWORD_HERE')
conn.getSchema()
```

**Comment by lifeisgoodcdj** [comment]
print(conn.gsql('''LS''', options=[]))
The result is same to "conn.gsql('ls', options=[])"

**Comment by lifeisgoodcdj** [comment]
> I think you could be missing the correct username and password. For example, this should be correct code:
> 
> ```python
> import pyTigerGraph as tg
> conn = tg.TigerGraphConnction(host="http://10.116.85.xxx", graphname='YOUR_GRAPH_NAME_HERE', username='YOUR_USERNAME_HERE', password='YOUR_PASSWORD_HERE')
> conn.getSchema()
> ```

now ,my code is here:
import pyTigerGraphBeta as tg
conn=tg.TigerGraphConnection(host='http://10.116.85.xxx', graphname='social', username='tigergraph', password='tigergraph')
conn.gsql('ls', option=[])

**Comment by lifeisgoodcdj** [comment]
HI，I've checked port 14240 on each node( all is 3)
But Still wrong with "conn.gaql('ls')" , meanwhile, other command is OK such as "conn.getVertexDataframe('person')" or "conn.getSchema()"
My question is : 
Do you test pyTigerGraphBeta by connecting to tigerDB( 3.0.6 or above) deployed on the cluster with 3 nodes ?  
Is it necessary to reduce the version to tigergraph 2.x.x ?
And what else can be done?



gadmin status : OK

port 14240 status:  seems OK



***@***.***
 
From: Parker Erickson
Date: 2021-03-30 12:33
To: pyTigerGraph/pyTigerGraph
CC: lifeisgoodcdj; Mention
Subject: Re: [pyTigerGraph/pyTigerGraph] Couldn't connect tigerDB (#31)
I think you are missing changing the hostname from "localhost" to your IP address specified, along with the graphname, username, and password. For example, this should be correct code:
import pyTigerGraph as tg
conn = tg.TigerGraphConnction(host="http://10.116.85.xxx", graphname='YOUR_GRAPH_NAME_HERE', username='YOUR_USERNAME_HERE', password='YOUR_PASSWORD_HERE')
conn.getSchema()

**Comment by zrougamed** [comment]
@lifeisgoodcdj I am @CST+6 can you confirm if we can have a session over zoom for debugging ?

**Comment by lifeisgoodcdj** [comment]
Sorry, session over zoom not allowed in my company



***@***.***
 
From: Zrouga Mohamed
Date: 2021-04-03 07:33
To: pyTigerGraph/pyTigerGraph
CC: lifeisgoodcdj; Mention
Subject: Re: [pyTigerGraph/pyTigerGraph] Couldn't connect tigerDB (#31)
@lifeisgoodcdj I am @cst+6 can you confirm if we can have a session over zoom for debugging ?

**Comment by louisza** [comment]
I can confirm. I have the exact same problem. I have code that worked on previous versions of pytigergraph but the switch to pytigerdriver broke that code.

`conn = tg.TigerGraphConnection(host="http://localhost",
                       graphname="money", 
                       username="tigergraph", 
                       password="tigergraph")
conn.gsql('ls')`

~/miniconda3/envs/graph_tiger/lib/python3.9/socket.py in create_connection(address, timeout, source_address)
    829             if source_address:
    830                 sock.bind(source_address)
--> 831             sock.connect(sa)
    832             # Break explicitly a reference cycle
    833             err = None

ConnectionRefusedError: [Errno 61] Connection refused

When I downgrade to PyTigerDriver==0.0.9.6.3 then the code executes without errors

**Comment by zrougamed** [comment]
@louisza please use this :+1: 

```
conn = tg.TigerGraphConnection(host="http://localhost", graphname="money", username="tigergraph", password="tigergraph",useCert=False)
conn.gsql('ls')
```

useCert = False that should work 
P.S : you're invited to upgrade the pyTigerGraph package
