### ISSUE TITLE
GSQL Doesn't Work with HTTPS boxes

### ISSUE THREAD

**Issue by parkererickson** [pyTigerGraph/pyTigerGraph#34]
**Describe the bug**
We want to produce secrets using pyTigerGraph. Currently, the package strips http:// and https:// information, leading the connection to not work.

**To Reproduce**
This is the offending line in the gsqlInit() function:

self.url = self.gsUrl.replace("https://", "").replace("http://", "")  # Getting URL with gsql port w/o https:// 

**Expected behavior**
Do not strip http:// and https:// from url in order to work with ssl secured connections.

**Comment by zrougamed** [comment]
this issue is solved in  v0.0.9.6.7
