### ISSUE TITLE
Cannot get token from TG 3.5.0

### ISSUE THREAD

**Issue by MaciejMJ** [pyTigerGraph/pyTigerGraph#52]
**Describe the bug**
TigerGraph 3.5.0 introduced a breaking change in the `/requesttoken` endpoint. It is not compatible with the latest version of pyTigerGraph.

https://docs.tigergraph.com/tigergraph-server/current/release-notes/#_compatibility_with_tigergraph_3_4

> GET /requesttoken endpoint is dropped. Please use POST /requesttoken to request authentication tokens instead.

**To Reproduce**
Try to use pyTigerGraph with TigerGraph 3.5 (restpp enabled).

**Expected behavior**
pyTigerGraph is able to connect to TigerGraph.

**Comment by zrougamed** [comment]
Hi @MaciejMJ 

Thanks ! the issues are fixed
