### ISSUE TITLE
GetToken - local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by vermamanoj** [pyTigerGraph/pyTigerGraph#56]
**Describe the bug**
When using GetToken function, it results in error - local variable 'res' referenced before assignment

**To Reproduce**
```
import pyTigerGraph as tg
import json

hostName = "http://localhost:14240"
userName = "xxxxxx”
password = "xxxxx”

conn = tg.TigerGraphConnection(host=hostName, username=userName, password=password, version="3.5.0") #tried without version as well)

print(conn.gsql('ls', options=[]))
# successful output till here 

graphName = "name...”
conn.graphname = graphName
secret = conn.createSecret()
token = conn.getToken(secret, setToken=True)[0]
```

**Expected behavior**
should get the token

**Screenshots**
---------------------------------------------------------------------------
```
UnboundLocalError                         Traceback (most recent call last)
/var/folders/1j/9t5qj_pn2hq3r_g_bmhbvpj40000gr/T/ipykernel_18660/2292407114.py in <module>
      2 conn.graphname = graphName
      3 secret = conn.createSecret()
----> 4 token = conn.getToken(secret, setToken=True)[0]
      5 
      6 print(token)

~/Library/Python/3.8/lib/python/site-packages/pyTigerGraph/pyTigerGraph.py in getToken(self, secret, setToken, lifetime)
   1402             except:
   1403                 tsuccess = False
-> 1404         if not res["error"]:
   1405             if setToken:
   1406                 self.apiToken = res["token"]

UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by parkererickson** [comment]
Got a few questions for you to try and diagnosis this:
What version of pyTigerGraph are you using?
It looks like you are running TigerGraph DB on your local machine, if not where are you running it?
Did you enable authentication on the TigerGraph DB?

Thanks!

**Comment by vermamanoj** [comment]
Pls find my answers:

- What version of pyTigerGraph are you using?
    pyTigerDriver==1.0.14
    pyTigerGraph==0.0.9.9.2

- It looks like you are running TigerGraph DB on your local machine, if not where are you running it?
  yes, locally on docker

- Did you enable authentication on the TigerGraph DB?
 I create different user (tigergraph2) and assigned observer, query reader/writer, designer and admin role on the given graph. I am using user tigergraph2 to to connect. 

Performed following two actions:
[Enable GSQL authentication](https://docs.tigergraph.com/tigergraph-server/current/user-access/enabling-user-authentication#_enable_gsql_authentication)

[Enable RESTPP authentication](https://docs.tigergraph.com/tigergraph-server/current/user-access/enabling-user-authentication#_enable_restpp_authentication)

**Comment by vermamanoj** [comment]
I followed this document to setup docker - https://docs.tigergraph.com/tigergraph-server/current/getting-started/docker

and trying to replicate this pattern - [https%3A%2F%2Fgithub.com%2FTigerGraph-DevLabs%2FTigerGraph_Northwinds](https://github.com/TigerGraph-DevLabs/TigerGraph_Northwinds)

I have changed the hostname (localhost:14240), username (tigergraph2) and password.

**Comment by parkererickson** [comment]
Oh, the hostname should be just `http://localhost`, as pyTigerGraph already adds the port numbers onto the requests based upon what port they use (some functions use 9000 and some use 14240). If you map your ports differently than default, then you will have to use the connection parameters accordingly.

**Comment by vermamanoj** [comment]
thanks, somehow I missed this part, closing the issue.
